FROM node:lts-alpine

WORKDIR /home/node/app

# Install deps
COPY ./package* ./

RUN npm install && \
    npm install -g knex && \
    npm cache clean --force

COPY . .

# Expose ports (for orchestrators and dynamic reverse proxies)
EXPOSE 3000

# Start the app
RUN chmod +x ./wait-for.sh;

RUN apk add netcat-openbsd;

CMD ./wait-for.sh mysql:3306 && \
    knex migrate:latest && \
    npm run start