/***CREATING ALL TABLES*/
CREATE TABLE `projects` (
  `UUID` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=INNODB;
CREATE TABLE `experiments` (
  `UUID` VARCHAR(255) NOT NULL,
  `ProjectId` VARCHAR(255) NOT NULL,
  `PipelineId` VARCHAR(255) NOT NULL,
  `DatasetId` VARCHAR(255) NOT NULL,
  `TargetColumnId` VARCHAR(255),
  `Parameters` LONGTEXT NOT NULL,
  `CreatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=INNODB;
CREATE TABLE `pipelines`
(
  `UUID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=INNODB;
CREATE TABLE `datasets`
(
  `UUID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=INNODB;
CREATE TABLE `columns`
(
  `UUID` VARCHAR(255) NOT NULL,
  `DatasetId` VARCHAR(255) NOT NULL,
  `DataType` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`UUID`)
) ENGINE=INNODB;

/******************************************************************/